### ISSUE TITLE
duolingo-review.user.js: Not ready yet...

### ISSUE THREAD

**Issue by gambhiro** [vaughanchandler/duolingo#2]
`duolingo-review.user.js` doesn't show the table at the end anymore, and keeps logging "Not ready yet..."

I have been using it for some time, it is very useful! It collected the sentences, I converted the table and imported to Anki.

I took a few days' break and when I continued the lessons, it stopped working.

Perhaps something changed in the DOM.

**Comment by gambhiro** [comment]
I ran a beautifier on the JS that duolingo loads, I can see that the API has changed a bit, for example `duo.SessionView` doesn't exist any more.

The functions such as `showEndView` are still around, but I can't see how to access them from the `duo` object.

**Comment by vaughanchandler** [comment]
I'm closing this as I've deprecated the script. Duolingo now provides it's own native review making my script obsolete.
