### ISSUE TITLE
Causes "too many requests" error message and temporary Duolingo account lockout

### ISSUE THREAD

**Issue by hughcharlesparker** [vaughanchandler/duolingo#4]
I installed duolingo-stats.user.js a week or so ago, and have since been getting locked out of my Duolingo account every now and then.  It took me a while to work out that this script was causing it.  It's a temporary thing, access comes back after a few hours.  In the mean time, instead of any Duolingo page, I just get a "too many requests" error.  Something in the script is causing so many Duolingo page loads that the servers have concluded that my account is a script-spam account.

There have been several other reports of this behaviour in the Duolingo forums.  Here's one of the discussions: https://www.duolingo.com/comment/17211394

**Comment by vaughanchandler** [comment]
This should be fixed in the latest version.
